'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ArrowRight, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';

interface ReceiverViewProps {
    inputCode: string;
    isConnecting: boolean;
    onInputChange: (value: string) => void;
    onJoin: () => void;
    onCancel: () => void;
}

export const ReceiverView = ({
    inputCode,
    isConnecting,
    onInputChange,
    onJoin,
    onCancel,
}: ReceiverViewProps) => (
    <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-10"
    >
        <div className="space-y-6 py-2">
            <div className="space-y-4 text-center">
                <Label
                    htmlFor="code-input"
                    className="text-xs font-black uppercase tracking-[0.3em] text-muted-foreground opacity-60"
                >
                    Target Access Key
                </Label>
                <div className="relative group">
                    <div className="absolute -inset-1 bg-linear-to-r from-primary/20 to-accent/20 rounded-2xl blur-lg transition duration-500 group-focus-within:opacity-100 opacity-0" />
                    <Input
                        id="code-input"
                        placeholder="ENTER 8-DIGIT KEY"
                        value={inputCode}
                        onChange={(e) =>
                            onInputChange(e.target.value.toUpperCase())
                        }
                        maxLength={8}
                        className="relative h-20 text-4xl font-black text-center tracking-[0.3em] rounded-2xl border-white/10 bg-white/5 backdrop-blur-md uppercase placeholder:tracking-[0.1em] placeholder:text-sm placeholder:font-bold focus-visible:ring-primary/50 focus-visible:border-primary/50 transition-all"
                        disabled={isConnecting}
                        autoFocus
                    />
                </div>
            </div>

            <div className="space-y-4">
                <Button
                    className="w-full h-16 text-lg font-bold rounded-2xl glow-primary shadow-xl shadow-primary/20 transition-all hover:scale-[1.02] active:scale-[0.98]"
                    disabled={inputCode.length !== 8 || isConnecting}
                    onClick={onJoin}
                >
                    <span className="flex items-center justify-center gap-3">
                        {isConnecting ? (
                            <>
                                <Loader2 className="w-6 h-6 animate-spin" />
                                Opening Tunnel...
                            </>
                        ) : (
                            <>
                                Establish Connection
                                <ArrowRight className="w-6 h-6 group-hover:translate-x-1 transition-transform" />
                            </>
                        )}
                    </span>
                </Button>

                <p className="text-[10px] text-center text-muted-foreground uppercase tracking-widest font-bold opacity-50">
                    Keys are generated by the sender and expire after use.
                </p>
            </div>
        </div>

        {isConnecting && (
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex justify-center"
            >
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={onCancel}
                    className="text-muted-foreground hover:text-destructive transition-colors"
                >
                    Abort Connection
                </Button>
            </motion.div>
        )}
    </motion.div>
);
